# Generated by Django 5.0.1 on 2024-02-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='desciption',
            new_name='description',
        ),
    ]
